"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.plans = void 0;
exports.plans = {
    free: {
        bots: 1,
        messages: 100,
        price: 0,
        productId: process.env.NODE_ENV === "production" ? "prod_7dlxu9H0z4nycn581YDH76" : "prod_3LNHH2Is2Pkk7KQgpm0wIy",
        features: [
            `🤖 1 AI bot`,
            "💬 100 messages/month",
            "📊 Basic analytics",
            "⏳ Queue priority: Standard",
            "🔒 Basic security",
            "🆘 Community support",
            "⏱️ Response time: <5s"
        ],
        name: "Free",
        description: "Perfect for hobbyists exploring AI chatbots. Get started with basic functionality at no cost.",
        badge: "Great for personal use",
        buttonText: "Start Free",
        buttonColor: "bg-blue-500",
        buttonTextColor: "text-white",
        buttonHoverColor: "hover:bg-blue-600",
        buttonHoverTextColor: "hover:text-white",
        buttonBorderColor: "border-blue-500",
        buttonBorderWidth: "border-2",
        buttonBorderRadius: "rounded-lg",
    },
    lite: {
        bots: 5,
        messages: 1000,
        price: 19,
        productId: "",
        features: [
            "🚀 5 AI bots",
            "💥 1,000 messages/month",
            "📈 Advanced analytics",
            "🛠️ Basic customizations",
            "🔌 3rd-party integrations",
            "⏳ Queue priority: High",
            "📧 Email support (24h response)",
            "🎯 AI accuracy boost",
            "⏱️ Response time: <2s"
        ],
        name: "Lite",
        description: "For growing businesses needing more capacity. Scale your AI operations with confidence.",
        badge: "Most Popular 💎",
        buttonText: "Go Pro →",
        buttonColor: "bg-green-500",
        buttonTextColor: "text-white",
        buttonHoverColor: "hover:bg-green-600",
        buttonHoverTextColor: "hover:text-white",
        buttonBorderColor: "border-green-500",
        buttonBorderWidth: "border-2",
        buttonBorderRadius: "rounded-lg",
    },
    business: {
        bots: 10,
        messages: 10000,
        price: 89,
        productId: process.env.NODE_ENV === "production" ? "prod_5MmBhFeoV8ux1Ajt2GmRCK" : "prod_4JSusrL2XiVARq9hMLGQeq",
        features: [
            "🌟 10 AI bots",
            "⚡ 10,000 messages/month",
            "🛠️ Full customization",
            "🔗 Unlimited integrations",
            "📞 Priority support (4h response)",
            "🔒 Enterprise-grade security",
            "📦 Custom AI model training",
            "👥 Team collaboration",
            "⏱️ Response time: <1s"
        ],
        name: "Business",
        description: "Enterprise-grade solution for mission-critical operations. Full customization and priority support.",
        badge: "Best Value 🏆",
        buttonText: "Scale Up ↗",
        buttonColor: "bg-purple-600",
        buttonTextColor: "text-white",
        buttonHoverColor: "hover:bg-purple-700",
        buttonHoverTextColor: "hover:text-white",
        buttonBorderColor: "border-purple-600",
        buttonBorderWidth: "border-2",
        buttonBorderRadius: "rounded-lg",
    },
    unlimited: {
        bots: Infinity,
        messages: Infinity,
        price: 200,
        productId: process.env.NODE_ENV === "production" ? "prod_9xdh9XQ1PHwcNVmYfZazj" : "prod_3dbgjMwLS3TmxTjSTxrWVn",
        features: [
            "🌈 Unlimited bots",
            "♾️ Unlimited messages",
            "🏅 Dedicated account manager",
            "⚙️ White-label solutions",
            "🔐 SOC 2 compliance",
            "📞 24/7 VIP support",
            "💡 Custom AI development",
            "📈 SLA-backed performance",
            "⏱️ Response time: <500ms"
        ],
        name: "Enterprise",
        description: "For organizations needing unlimited scale and premium support. Tailored AI solutions with SLAs.",
        badge: "Premium Tier 👑",
        buttonText: "Contact Sales 👋",
        buttonColor: "bg-gradient-to-r from-amber-500 to-orange-600",
        buttonTextColor: "text-white",
        buttonHoverColor: "hover:opacity-90",
        buttonHoverTextColor: "hover:text-white",
        buttonBorderColor: "border-orange-500",
        buttonBorderWidth: "border-2",
        buttonBorderRadius: "rounded-lg",
    }
};
