export const plans = {
    free: {
      bots: 1,
      messages: 100,
      price: 0,
      url: `https://checkout.dodopayments.com/buy/{productid}?quantity=1&redirect_url={your website return_url}`,
      features: [
        `🤖 1 AI bot`,
        "💬 100 messages/month",
        "📊 Basic analytics",
        "⏳ Queue priority: Standard",
        "🔒 Basic security",
        "🆘 Community support",
        "⏱️ Response time: <5s"
      ],
      name: "Free",
      description: "Perfect for hobbyists exploring AI chatbots. Get started with basic functionality at no cost.",
      badge: "Great for personal use",
      buttonText: "Start Free",
      buttonColor: "bg-blue-500",
      buttonTextColor: "text-white",
      buttonHoverColor: "hover:bg-blue-600",
      buttonHoverTextColor: "hover:text-white",
      buttonBorderColor: "border-blue-500",
      buttonBorderWidth: "border-2",
      buttonBorderRadius: "rounded-lg",
    },
    pro: {
      bots: 5,
      messages: 1000,
      price: 19,
      url: `https://checkout.dodopayments.com/buy/{productid}?quantity=1&redirect_url={your website return_url}`,
      features: [
        "🚀 5 AI bots", 
        "💥 1,000 messages/month",
        "📈 Advanced analytics",
        "🛠️ Basic customizations",
        "🔌 3rd-party integrations",
        "⏳ Queue priority: High",
        "📧 Email support (24h response)",
        "🎯 AI accuracy boost",
        "⏱️ Response time: <2s"
      ],
      name: "Professional",
      description: "For growing businesses needing more capacity. Scale your AI operations with confidence.",
      badge: "Most Popular 💎",
      buttonText: "Go Pro →",
      buttonColor: "bg-green-500",
      buttonTextColor: "text-white",
      buttonHoverColor: "hover:bg-green-600",
      buttonHoverTextColor: "hover:text-white",
      buttonBorderColor: "border-green-500",
      buttonBorderWidth: "border-2",
      buttonBorderRadius: "rounded-lg",
    },
    business: {
      bots: 10,
      messages: 10000,
      price: 89,
      url: `https://checkout.dodopayments.com/buy/{productid}?quantity=1&redirect_url={your website return_url}`,
      features: [
        "🌟 10 AI bots",
        "⚡ 10,000 messages/month", 
        "🛠️ Full customization",
        "🔗 Unlimited integrations",
        "📞 Priority support (4h response)",
        "🔒 Enterprise-grade security",
        "📦 Custom AI model training",
        "👥 Team collaboration",
        "⏱️ Response time: <1s"
      ],
      name: "Business",
      description: "Enterprise-grade solution for mission-critical operations. Full customization and priority support.",
      badge: "Best Value 🏆",
      buttonText: "Scale Up ↗",
      buttonColor: "bg-purple-600",
      buttonTextColor: "text-white",
      buttonHoverColor: "hover:bg-purple-700",
      buttonHoverTextColor: "hover:text-white",
      buttonBorderColor: "border-purple-600",
      buttonBorderWidth: "border-2",
      buttonBorderRadius: "rounded-lg",
    },
    unlimited: {
      bots: Infinity,
      messages: Infinity,
      price: 200,
      url: `https://checkout.dodopayments.com/buy/{productid}?quantity=1&redirect_url={your website return_url}`,
      features: [
        "🌈 Unlimited bots",
        "♾️ Unlimited messages",
        "🏅 Dedicated account manager",
        "⚙️ White-label solutions",
        "🔐 SOC 2 compliance",
        "📞 24/7 VIP support",
        "💡 Custom AI development",
        "📈 SLA-backed performance",
        "⏱️ Response time: <500ms"
      ],
      name: "Enterprise",
      description: "For organizations needing unlimited scale and premium support. Tailored AI solutions with SLAs.",
      badge: "Premium Tier 👑",
      buttonText: "Contact Sales 👋",
      buttonColor: "bg-gradient-to-r from-amber-500 to-orange-600",
      buttonTextColor: "text-white",
      buttonHoverColor: "hover:opacity-90",
      buttonHoverTextColor: "hover:text-white",
      buttonBorderColor: "border-orange-500",
      buttonBorderWidth: "border-2",
      buttonBorderRadius: "rounded-lg",
    }
  }